# Generated by Django 5.1.7 on 2025-03-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=50)),
                ('package_price', models.FloatField()),
                ('package_description', models.TextField()),
                ('place_name', models.CharField(max_length=50)),
                ('package_image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
