# Generated by Django 5.1.7 on 2025-03-09 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=50)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('journey_date', models.DateField()),
                ('total_persons', models.IntegerField()),
                ('pickup_location', models.CharField(max_length=50)),
                ('pickup_time', models.TimeField()),
                ('book_now', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.package')),
            ],
        ),
    ]
