# Generated by Django 5.1.7 on 2025-03-09 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user_email',
        ),
    ]
